LineLength:
  Enabled: false

MethodLength:
  Enabled: false

BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

NumericLiteralPrefix:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets
